### ISSUE TITLE
cant download 1.12.2-7.0.0-BETA-349

### ISSUE THREAD

**Issue by Mahagon** [terencewestphal/docker-minecraft-spongevanilla#3]
Hey! awesome project :)

i got a problem with running the latest sponge version

`docker build --build-arg VERSION=1.12.2-7.0.0-BETA-349 -t minecraft-spongevanilla .`
That commands downloads the correct version asyo u can see here:

`Status: Downloaded newer image for terencewestphal/minecraft:1.12.1
 ---> 951508ddf82c
Step 2 : LABEL maintainer "Terence Westphal"
 ---> Running in ca823fcc16a3
 ---> 8e3013a1f96c
Removing intermediate container ca823fcc16a3
Step 3 : ARG VERSION=1.12.2-7.0.0-BETA-349
 ---> Running in 9ba9c174f69e
 ---> 95f469b273d3
Removing intermediate container 9ba9c174f69e
Step 4 : ENV SPONGE_VERSION ${VERSION}
 ---> Running in 0a8b7dcc6302
 ---> e7d497325c7e
Removing intermediate container 0a8b7dcc6302
Step 5 : ENV PACKAGE "/opt/minecraft"
 ---> Running in 7b3c6dc2aad0
 ---> 3b205dbc0c7c
Removing intermediate container 7b3c6dc2aad0
Step 6 : ENV JAR "spongevanilla-${SPONGE_VERSION}.jar"
 ---> Running in 91a24a4c0790
 ---> ce02bb6254d7
Removing intermediate container 91a24a4c0790
Step 7 : ENV JAR_OPT ""
 ---> Running in 9fb50160398a
 ---> 6a05bc4f7017
Removing intermediate container 9fb50160398a
`
but it finaly runs  java -Xms10010M -Xmx10010M -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalPacing -XX:+AggressiveOpts -jar /opt/minecraft/spongevanilla-1.12.1-7.0.0-BETA-316.jar

**Comment by terencewestphal** [comment]
Unfortunately I could not reproduce this error. 

But since it was time to update to the latest version of SpongeVanilla anyway, I made a new releases: https://github.com/terencewestphal/docker-minecraft-spongevanilla/releases/tag/1.12.2-7.0.0-BETA-369 

I hope this solves your problem.
